### PR TITLE
feat: trail of bits audit

### PR DESCRIPTION
**Pull request by philburrrt**

### CODE REVIEW

**Comment by lehnberg** [comment]
@philburrrt the audit is in the wrong section. 

currently: under strategies audits

should be: under v2 vault audits

Separately, you might also want to consider using a table to host the audits. This way you could have a date column as well.

**Review by lehnberg — CHANGES_REQUESTED** [review]
See comment in PR

**Comment by philburrrt** [comment]
@lehnberg moved to v2 vault audits. will add turning this into a table to my to-do list. thanks.

**Review by lehnberg — CHANGES_REQUESTED** [review]
Seems like Trail of Bits audit is still incorrectly under strategies. 

Also noticed that liquity audit is under vaults, but probably should be under strategies.

**Comment by philburrrt** [comment]
@lehnberg fixed, my apologies

**Review by lehnberg — APPROVED** [review]

**Pull request merged**
